update

diff --git a/buildroot/bin/build_all_examples b/buildroot/bin/build_all_examples
--- a/buildroot/bin/build_all_examples
+++ b/buildroot/bin/build_all_examples
@@ -1,101 +1,222 @@
 #!/usr/bin/env bash
 #
-# build_all_examples base_branch [resume_point]
+# Usage:
 #
+#  build_all_examples [-a|--archive]         - Copy the binary to the export location
+#                     [-B|--base]            - Base path of configurations, overriding -b
+#                     [-b|--branch=<branch>] - Branch to fetch from Configurations repo (import-2.1.x)
+#                     [-c|--continue]        - Continue the paused build
+#                     [-d|-v|--debug]        - Print extra debug output (after)
+#                     [-e|--export=N]        - Set CONFIG_EXPORT and export to the export location
+#                     [-f|--nofail]          - Don't stop on a failed build
+#                     [-h|--help]            - Print usage and exit
+#                     [-l|--limit=#]         - Limit the number of builds in this run
+#                     [-m|--many]            - Build all the environments for each example
+#                     [-n|--nobuild]         - Don't actually build anything
+#                     [-o|--output]          - Redirect export / archiving to another location
+#                                              (By default export to origin config folders)
+#                     [-p|--purge]           - Purge the status file and start over
+#                     [-r|--resume=<path>]   - Start at some config in the filesystem order
+#                     [-s|--skip]            - Continue the paused build, skipping one
+#
+
+HERE=`dirname $0`
+PATH="$HERE:$PATH"
+
+. mfutil
 
 GITREPO=https://github.com/MarlinFirmware/Configurations.git
 STAT_FILE=./.pio/.buildall
 
-# Check dependencies
-which curl 1>/dev/null 2>&1 || { echo "curl not found! Please install it."; exit ; }
-which git 1>/dev/null 2>&1 || { echo "git not found! Please install it."; exit ; }
+usage() { echo "Usage:
 
-SED=$(command -v gsed 2>/dev/null || command -v sed 2>/dev/null)
-[[ -z "$SED" ]] && { echo "No sed found, please install sed" ; exit 1 ; }
+build_all_examples [-a|--archive]         - Copy the binary to the export location
+                   [-B|--base]            - Base path of configurations, overriding -b
+                   [-b|--branch=<branch>] - Branch to fetch from Configurations repo (import-2.1.x)
+                   [-c|--continue]        - Continue the paused build
+                   [-d|-v|--debug]        - Print extra debug output (after)
+                   [-e|--export=N]        - Set CONFIG_EXPORT and export to the export location
+                   [-f|--nofail]          - Don't stop on a failed build
+                   [-h|--help]            - Print usage and exit
+                   [-l|--limit=#]         - Limit the number of builds in this run
+                   [-m|--many]            - Build all the environments for each example
+                   [-n|--nobuild]         - Don't actually build anything
+                   [-o|--output]          - Redirect export / archiving to another location
+                                            (By default export to origin config folders)
+                   [-p|--purge]           - Purge the status file and start over
+                   [-r|--resume=<path>]   - Start at some config in the filesystem order
+                   [-s|--skip]            - Continue the paused build, skipping one
+"
+}
 
-SELF=`basename "$0"`
-HERE=`dirname "$0"`
-
-# Check if called in the right location
-[[ -e "Marlin/src" ]] || { echo -e "This script must be called from a Marlin working copy with:\n ./buildroot/bin/$SELF $1" ; exit ; }
-
-if [[ $# -lt 1 || $# -gt 2 ]]; then
-  echo "Usage: $SELF base_branch [resume_point]
-  base_branch  - Configuration branch to download and build
-  resume_point - Configuration path to start from"
-  exit
-fi
-
-echo "This script downloads all Configurations and builds Marlin with each one."
-echo "On failure the last-built configs will be left in your working copy."
-echo "Restore your configs with 'git checkout -f' or 'git reset --hard HEAD'."
-
-unset BRANCH
+# Assume the most recent configs
+BRANCH=import-2.1.x
 unset FIRST_CONF
-if [[ -f "$STAT_FILE" ]]; then
-  IFS='*' read BRANCH FIRST_CONF <"$STAT_FILE"
-fi
+EXIT_USAGE=
+LIMIT=1000
+
+while getopts 'aB:b:cde:fhl:mno:pr:sv-:' OFLAG; do
+  case "${OFLAG}" in
+    a) ARCHIVE=1                ; bugout "Archiving" ;;
+    B) CBASE=${OPTARG%/}        ; bugout "Base: $CBASE" ;;
+    b) BRANCH=$OPTARG           ; bugout "Branch: $BRANCH" ;;
+    c) CONTINUE=1               ; bugout "Continue" ;;
+  d|v) DEBUG=1                  ; bugout "Debug ON" ;;
+    e) CEXPORT=$OPTARG          ; bugout "Export $CEXPORT" ;;
+    f) NOFAIL=1                 ; bugout "Continue on Fail" ;;
+    h) EXIT_USAGE=1 ; break ;;
+    l) LIMIT=$OPTARG            ; bugout "Limit to $LIMIT build(s)" ;;
+    m) MANY=1                   ; bugout "Many Envs" ;;
+    n) DRYRUN=1                 ; bugout "Dry Run" ;;
+    o) OUTBASE="${OPTARG%/}"    ; bugout "Archive to $OUTBASE" ;;
+    p) PURGE=1                  ; bugout "Purge stat file" ;;
+    r) ISRES=1 ; FIRST_CONF=$OPTARG ; bugout "Resume: $FIRST_CONF" ;;
+    s) CONTSKIP=1               ; bugout "Continue, skipping" ;;
+    -) ONAM="${OPTARG%%=*}" ; OVAL="${OPTARG#*=}"
+       case "$ONAM" in
+      archive) ARCHIVE=1        ; bugout "Archiving" ;;
+         base) CBASE=${OVAL%/}  ; bugout "Base: $CBASE" ;;
+       branch) BRANCH=$OVAL     ; bugout "Branch: $BRANCH" ;;
+         many) MANY=1           ; bugout "Many Envs" ;;
+       nofail) NOFAIL=1         ; bugout "Continue on Fail" ;;
+       resume) ISRES=1 ; FIRST_CONF=$OVAL ; bugout "Resume: $FIRST_CONF" ;;
+     continue) CONTINUE=1       ; bugout "Continue" ;;
+         skip) CONTSKIP=1       ; bugout "Continue, skipping" ;;
+       export) CEXPORT=$OVAL    ; bugout "Export $EXPORT" ;;
+       output) OUTBASE="${OVAL%/}" ; bugout "Archive to $OUTBASE" ;;
+        limit) LIMIT=$OVAL      ; bugout "Limit to $LIMIT build(s)" ;;
+         help) [[ -z "$OVAL" ]] || perror "option can't take value $OVAL" $ONAM ; EXIT_USAGE=1 ;;
+        debug) DEBUG=1          ; bugout "Debug ON" ;;
+      nobuild) DRYRUN=1         ; bugout "Dry Run" ;;
+        purge) PURGE=1          ; bugout "Purge stat file" ;;
+            *) EXIT_USAGE=2 ; echo "$SELF: unrecognized option \`--$ONAM'" ; break ;;
+       esac
+       ;;
+    *) EXIT_USAGE=2 ; break ;;
+  esac
+done
+shift $((OPTIND - 1))
+
+# Check for mixed continue, skip, resume arguments. Only one should be used.
+((CONTINUE + CONTSKIP + ISRES + PURGE > 1)) && { echo "Don't mix -c, -p, -s, and -r options" ; echo ; EXIT_USAGE=2 ; }
+
+# Exit with helpful usage information
+((EXIT_USAGE)) && { usage ; let EXIT_USAGE-- ; exit $EXIT_USAGE ; }
+
+echo
+echo "This script downloads all example configs and attempts to build them."
+echo "On failure the last-built configs are left in your working copy."
+echo "Restore your configs with 'git checkout -f' or 'git reset --hard HEAD'."
+echo
+
+[[ -n $PURGE ]] && rm -f "$STAT_FILE"
+[[ -z $FIRST_CONF && -f "$STAT_FILE" ]] && IFS='*' read BRANCH FIRST_CONF <"$STAT_FILE"
 
 # If -c is given start from the last attempted build
-if [[ $1 == '-c' ]]; then
+if ((CONTINUE)); then
   if [[ -z $BRANCH || -z $FIRST_CONF ]]; then
     echo "Nothing to continue"
     exit
   fi
-elif [[ $1 == '-s' ]]; then
+elif ((CONTSKIP)); then
   if [[ -n $BRANCH && -n $FIRST_CONF ]]; then
     SKIP_CONF=1
   else
     echo "Nothing to skip"
     exit
   fi
-else
-  BRANCH=${1:-"import-2.0.x"}
-  FIRST_CONF=$2
 fi
 
 # Check if the current repository has unmerged changes
-if [[ $SKIP_CONF ]]; then
+if ((SKIP_CONF)); then
   echo "Skipping $FIRST_CONF"
-elif [[ $FIRST_CONF ]]; then
+elif [[ -n $FIRST_CONF ]]; then
   echo "Resuming from $FIRST_CONF"
 else
   git diff --quiet || { echo "The working copy is modified. Commit or stash changes before proceeding."; exit ; }
 fi
 
-# Create a temporary folder inside .pio
-TMP=./.pio/build-$BRANCH
-[[ -d "$TMP" ]] || mkdir -p $TMP
-
-# Download Configurations into the temporary folder
-if [[ ! -e "$TMP/README.md" ]]; then
-  echo "Downloading Configurations from GitHub into $TMP"
-  git clone --depth=1 --single-branch --branch "$BRANCH" $GITREPO "$TMP" || { echo "Failed to clone the configuration repository"; exit ; }
+# Check for the given base path
+if [[ -n $CBASE ]]; then
+  CBASE="${CBASE/#\~/$HOME}"
+  [[ -d "$CBASE" ]] || { echo "Given base -B $CBASE not found." ; exit ; }
 else
-  echo "Using previously downloaded Configurations at $TMP"
+  # Make a Configurations temporary folder if needed
+  CBASE=./.pio/build-$BRANCH
+  [[ -d "$CBASE" ]] || mkdir -p "$CBASE"
+  # Download the specified Configurations branch if needed
+  if [[ ! -e "$CBASE/README.md" ]]; then
+    echo "Fetching Configurations from GitHub to $CBASE"
+    git clone --depth=1 --single-branch --branch "$BRANCH" $GITREPO "$CBASE" || { echo "Failed to clone the configuration repository"; exit ; }
+  fi
 fi
 
-echo -e "Start building now...\n====================="
+# Build
+echo -e "=====================\nProceed with builds...\n====================="
 shopt -s nullglob
-IFS='
-'
-CONF_TREE=$( ls -d "$TMP"/config/examples/*/ "$TMP"/config/examples/*/*/ "$TMP"/config/examples/*/*/*/ "$TMP"/config/examples/*/*/*/*/ | grep -vE ".+\.(\w+)$" )
-DOSKIP=0
-for CONF in $CONF_TREE ; do
+
+export PAUSE=1
+
+# Get a list of all folders that contain a file matching "Configuration*.h"
+find "$CBASE"/config/examples -type d -name 'Configuration.h' -o -name 'Configuration_adv.h' -print0 \
+  | LC_ALL=C sort -fz \
+  | while IFS= read -r -d $'\0' CONF; do
+
+  # Remove the file name and slash from the end of the path
+  CONF=${CONF%/*}
+
   # Get a config's directory name
-  DIR=$( echo $CONF | sed "s|$TMP/config/examples/||" )
+  DIR=${CONF#$CBASE/config/examples/}
+
   # If looking for a config, skip others
-  [[ $FIRST_CONF ]] && [[ $FIRST_CONF != $DIR && "$FIRST_CONF/" != $DIR ]] && continue
+  [[ $FIRST_CONF ]] && [[ $FIRST_CONF != $DIR && "$FIRST_CONF/" != $DIR ]] && { ((DEBUG)) && echo "[SKIP] $DIR" ; continue ; }
   # Once found, stop looking
   unset FIRST_CONF
+
   # If skipping, don't build the found one
   [[ $SKIP_CONF ]] && { unset SKIP_CONF ; continue ; }
-  # ...if skipping, don't build this one
-  compgen -G "${CONF}Con*.h" > /dev/null || continue
-  echo "${BRANCH}*${DIR}" >"$STAT_FILE"
-  "$HERE/build_example" "internal" "$TMP" "$DIR" || { echo "Failed to build $DIR"; exit ; }
+
+  # Either Configuration.h or Configuration_adv.h must exist
+  [[ -f "$CONF"/Configuration.h || -f "$CONF"/Configuration_adv.h ]] || { echo "[NONE] $DIR" ; continue ; }
+
+  # Command arguments for 'build_example'
+  CARGS=("-b" "$CBASE" "-c" "$DIR")
+
+  # Exporting? Add -e argument
+  ((CEXPORT)) && CARGS+=("-e" "$CEXPORT")
+
+  # Build many environments? Add -m argument
+  ((MANY)) && CARGS+=("-m")
+
+  # Continue on fail? Add -f argument
+  ((NOFAIL)) && CARGS+=("-f")
+
+  # Archive the build? Add -a argument
+  ((ARCHIVE)) && CARGS+=("-a")
+
+  # Redirecting the export/archive output? Add -o argument
+  [[ -n $OUTBASE ]] && CARGS+=("-o" "$OUTBASE")
+
+  # Build or print build command for --nobuild
+  if ((DRYRUN)); then
+    echo -e "\033[0;32m[DRYRUN] build_example ${CARGS[@]}\033[0m"
+  else
+    # Remember where we are in case of failure
+    echo "${BRANCH}*${DIR}" >"$STAT_FILE"
+    ((DEBUG)) && echo "build_example ${CARGS[@]}"
+    # Invoke build_example
+    build_example "${CARGS[@]}" || { echo "Failed to build $DIR" ; exit ; }
+  fi
+
+  echo
+  ((--LIMIT)) || { echo "Specified limit reached" ; break ; }
+  echo
+
+  export PAUSE=0
+
 done
 
-# Delete the temp folder and build state
-[[ -e "$TMP/config/examples" ]] && rm -rf "$TMP"
-rm "$STAT_FILE"
+echo "Exiting"
+
+# Delete the build state if not paused early
+((PAUSE)) || rm -f "$STAT_FILE"
diff --git a/buildroot/bin/mftest b/buildroot/bin/mftest
--- a/buildroot/bin/mftest
+++ b/buildroot/bin/mftest
@@ -3,10 +3,12 @@
 #  mftest                             Select a test to apply and build
 #  mftest -b [#]                      Build the auto-detected environment
 #  mftest -u [#]                      Upload the auto-detected environment
-#  mftest [name] [index] [-y]         Set config options and optionally build a test
+#  mftest -tname -n# [-y]             Set config options and optionally build a test
 #
 
 [[ -d Marlin/src ]] || { echo "Please 'cd' to the Marlin repo root." ; exit 1 ; }
+
+which pio >/dev/null || { echo "Make sure 'pio' is in your execution PATH." ; exit 1 ;  }
 
 perror() { echo -e "$0: \033[0;31m$1 -- $2\033[0m" ; }
 errout() { echo -e "\033[0;31m$1\033[0m" ; }
@@ -14,35 +16,38 @@ bugout() { ((DEBUG)) && echo -e "\033[0;32m$1\033[0m" ; }
 
 usage() {
   echo "
-Usage: mftest [-t|--env=<env|index>] [-n|--num=<num>] [-m|--make] [-y|--build=<Y|n>]
-       mftest [-a|--autobuild]
+Usage: mftest [-a|--autobuild]
        mftest [-r|--rebuild]
+       mftest [-s|--silent]
+       mftest [-t|--env=<env|index>] [-n|--num=<num>] [-m|--make] [-y|--build=<Y|n>]
        mftest [-u|--autoupload] [-n|--num=<num>]
 
 OPTIONS
-  -t --env         The environment to apply / run, or the menu index number.
-  -n --num         The index of the test to run. (In file order.)
-  -m --make        Use the make / Docker method for the build.
-  -y --build       Skip 'Do you want to build this test?' and assume YES.
-  -h --help        Print this help.
   -a --autobuild   PIO Build using the MOTHERBOARD environment.
+  -d --default     Restore to defaults before applying configs.
+  -h --help        Print this help.
+  -m --make        Use the make / Docker method for the build.
+  -n --num         The index of the test to run. (In file order.)
+  -r --rebuild     Rebuild previous PIO Build.
+  -s --silent      Silence build output from PlatformIO.
+  -t --env         The environment to apply / run, or the menu index number.
   -u --autoupload  PIO Upload using the MOTHERBOARD environment.
   -v --verbose     Extra output for debugging.
-  -s --silent      Silence build output from PlatformIO.
+  -y --build       Skip 'Do you want to build this test?' and assume YES.
 
-env shortcuts: tree due esp lin lpc|lpc8 lpc9 m128 m256|mega stm|f1 f4 f7 s6 teensy|t31|t32 t35|t36 t40|t41
+env shortcuts: tree due esp lin lp8|lpc8 lp9|lpc9 m128 m256|mega stm|f1 f4 f7 s6 teensy|t31|t32 t35|t36 t40|t41
 "
 }
 
 TESTPATH=buildroot/tests
 
 STATE_FILE="./.pio/.mftestrc"
-SED=$(which gsed || which sed)
 
 shopt -s extglob nocasematch
 
 # Matching patterns
 ISNUM='^[0-9]+$'
+ISRST='^(restore)_'
 ISCMD='^(restore|opt|exec|use|pins|env)_'
 ISEXEC='^exec_'
 ISCONT='\\ *$'
@@ -52,9 +57,10 @@ TESTENV='-'
 CHOICE=0
 DEBUG=0
 
-while getopts 'abhmruvyn:t:-:' OFLAG; do
+while getopts 'adhmn:rst:uvy-:' OFLAG; do
   case "${OFLAG}" in
     a) AUTO_BUILD=1 ; bugout "Auto-Build target..." ;;
+    d) DL_DEFAULTS=1 ; bugout "Restore to defaults..." ;;
     h) EXIT_USAGE=1 ;;
     m) USE_MAKE=1 ; bugout "Using make with Docker..." ;;
     n) case "$OPTARG" in
@@ -68,7 +74,7 @@ while getopts 'abhmruvyn:t:-:' OFLAG; do
     u) AUTO_BUILD=2      ; bugout "Auto-Upload target..." ;;
     v) DEBUG=1           ; bugout "Debug ON" ;;
     y) BUILD_YES='Y'     ; bugout "Build will initiate..." ;;
-    -) IFS="=" read -r ONAM OVAL <<< "$OPTARG"
+    -) ONAM="${OPTARG%%=*}" ; OVAL="${OPTARG#*=}"
        case "$ONAM" in
          help) [[ -z "$OVAL" ]] || perror "option can't take value $OVAL" $ONAM ; EXIT_USAGE=1 ;;
     autobuild) AUTO_BUILD=1 ; bugout "Auto-Build target..."  ;;
@@ -84,8 +90,10 @@ while getopts 'abhmruvyn:t:-:' OFLAG; do
                esac
                ;;
       rebuild) REBUILD=1  ; bugout "Rebuilding previous..." ;;
+       silent) SILENT_FLAG="-s" ;;
          make) USE_MAKE=1 ; bugout "Using make with Docker..." ;;
 debug|verbose) DEBUG=1    ; bugout "Debug ON" ;;
+      default) DL_DEFAULTS=1 ; bugout "Restore to defaults..." ;;
         build) case "$OVAL" in
                  ''|y|yes) BUILD_YES='Y' ;;
                      n|no) BUILD_YES='N' ;;
@@ -99,6 +107,7 @@ debug|verbose) DEBUG=1    ; bugout "Debug ON" ;;
     *) EXIT_USAGE=2 ;;
   esac
 done
+shift $((OPTIND - 1))
 
 ((EXIT_USAGE)) && { usage ; let EXIT_USAGE-- ; exit $EXIT_USAGE ; }
 
@@ -133,7 +142,7 @@ lp9|lpc9) TESTENV='LPC1769' ;;
      t36) TESTENV='teensy35' ;;
      t40) TESTENV='teensy41' ;;
      t41) TESTENV='teensy41' ;;
-[1-9][1-9]|[1-9]) TESTNUM=$TESTENV ; TESTENV=- ;;
+[1-9]|[1-9][0-9]) TESTNUM=$TESTENV ; TESTENV=- ;;
 esac
 
 if ((AUTO_BUILD)); then
@@ -150,13 +159,19 @@ if ((AUTO_BUILD)); then
          *) SYS='uni' ;;
   esac
   echo ; echo -n "Auto " ; ((AUTO_BUILD == 2)) && echo "Upload..." || echo "Build..."
-  MB=$( grep -E "^\s*#define MOTHERBOARD" Marlin/Configuration.h | awk '{ print $3 }' | $SED 's/BOARD_//' )
+
+  #
+  # Get the MOTHERBOARD define value from the .h file and strip off the "BOARD_" prefix
+  #
+  ACODE='/^[[:space:]]*#define[[:space:]]MOTHERBOARD[[:space:]]/ { sub(/^BOARD_/, "", $3); print $3 }'
+  MB=$(awk "$ACODE" Marlin/Configuration.h 2>/dev/null)
+  [[ -z $MB ]] && MB=$(awk "$ACODE" Marlin/Config.h 2>/dev/null)
   [[ -z $MB ]] && { echo "Error - Can't read MOTHERBOARD setting." ; exit 1 ; }
   BLINE=$( grep -E "define\s+BOARD_$MB\b" Marlin/src/core/boards.h )
-  BNUM=$( $SED -E 's/^.+BOARD_[^ ]+ +([0-9]+).+$/\1/' <<<"$BLINE" )
-  BDESC=$( $SED -E 's/^.+\/\/ *(.+)$/\1/' <<<"$BLINE" )
-  [[ -z $BNUM ]] && { echo "Error - Can't find $MB in boards list." ; exit 1 ; }
-  ENVS=( $( grep -EA1 "MB\(.*\b$MB\b.*\)" Marlin/src/pins/pins.h | grep -E "#include.+//.+(env|$SYS):[^ ]+" | grep -oE "(env|$SYS):[^ ]+" | $SED -E "s/(env|$SYS)://" ) )
+  BNUM=$( sed -E 's/^.+BOARD_[^ ]+ +([0-9]+).+$/\1/' <<<"$BLINE" )
+  BDESC=$( sed -E 's/^.+\/\/ *(.+)$/\1/' <<<"$BLINE" )
+  [[ -z $BNUM ]] && { echo "Error - Can't find BOARD_$MB in core/boards.h." ; exit 1 ; }
+  ENVS=( $( grep -EA1 "MB\(.*\b$MB\b.*\)" Marlin/src/pins/pins.h | grep -E "#include.+//.+(env|$SYS):[^ ]+" | grep -oE "(env|$SYS):[^ ]+" | sed -E "s/(env|$SYS)://" ) )
   [[ -z $ENVS ]] && { errout "Error - Can't find target(s) for $MB ($BNUM)." ; exit 1 ; }
   ECOUNT=${#ENVS[*]}
 
@@ -181,9 +196,12 @@ if ((AUTO_BUILD)); then
       fi
     else
       echo "Detected \"$BDESC\" | $MB ($BNUM)."
-      [[ $CHOICE > $ECOUNT ]] && { echo "Environment selection out of range." ; exit 1 ; }
+      [[ $CHOICE > $ECOUNT ]] && { echo "Environment selection out of range." ; exit 66 ; }
     fi
     TARGET="${ENVS[$CHOICE-1]}"
+    if [[ $MB == 'SIMULATED' && $TARGET == 'linux_native' ]]; then
+      TARGET="simulator_linux_release" # Skip the linux_native environment
+    fi
     echo "Selected $TARGET"
   fi
 
@@ -196,7 +214,7 @@ if ((AUTO_BUILD)); then
     echo "Building environment $TARGET for board $MB ($BNUM)..." ; echo
     pio run $SILENT_FLAG -e $TARGET
   fi
-  exit 0
+  exit $?
 fi
 
 #
@@ -206,13 +224,26 @@ fi
 if [[ $TESTENV == '-' ]]; then
   IND=0
   NAMES=()
-  for FILE in $( ls -1 $TESTPATH/* )
+  MENU=()
+  BIGLEN=0
+  for FILE in $( ls -1 $TESTPATH/* | sort -f )
   do
     let IND++
     TNAME=${FILE/$TESTPATH\//}
     NAMES+=($TNAME)
-    (( IND < 10 )) && echo -n " "
-    echo " $IND) $TNAME"
+    IFS=""
+    ITEM=$( printf "%2i) %s" $IND $TNAME )
+    MENU+=($ITEM)
+    [[ ${#ITEM} -gt $BIGLEN ]] && BIGLEN=${#ITEM}
+  done
+
+  (( BIGLEN += 2 ))
+  THIRD=$(( (${#MENU[@]} + 2) / 3 ))
+  for ((i = 0; i < $THIRD; i++))
+  do
+    COL1=$i ; COL2=$(( $i + $THIRD )) ; COL3=$(( $i + 2 * $THIRD ))
+    FMT="%-${BIGLEN}s"
+    printf "${FMT}${FMT}${FMT}\n" ${MENU[$COL1]} ${MENU[$COL2]} ${MENU[$COL3]}
   done
 
   echo
@@ -249,7 +280,7 @@ if [[ $CHOICE == 0 ]]; then
     while IFS= read -r LINE
     do
       if [[ $LINE =~ $ISEXEC ]]; then
-        DESC=$( "$SED" -E 's/^exec_test \$1 \$2 "([^"]+)".*$/\1/g' <<<"$LINE" )
+        DESC=$( sed -E 's/^exec_test \$1 \$2 "([^"]+)".*$/\1/g' <<<"$LINE" )
         (( ++IND < 10 )) && echo -n " "
         echo " $IND) $DESC"
       fi
@@ -266,6 +297,11 @@ if [[ $CHOICE == 0 ]]; then
     done
   fi
 fi
+
+#
+# Restore to defaults if requested
+#
+((DL_DEFAULTS)) && use_example_configs
 
 #
 # Run the specified test lines
@@ -288,7 +324,8 @@ echo "$OUT" | {
         }
         ((IND == CHOICE)) && {
           GOTX=1
-          [[ $CMD == "" ]] && CMD="$LINE" || CMD=$( echo -e "$CMD$LINE" | $SED -e 's/\\//g' | $SED -E 's/ +/ /g' )
+          [[ -n $DL_DEFAULTS && $LINE =~ $ISRST ]] && LINE="use_example_configs"
+          [[ $CMD == "" ]] && CMD="$LINE" || CMD=$( echo -e "$CMD$LINE" | sed -e 's/\\//g' | sed -E 's/ +/ /g' )
           [[ $LINE =~ $ISCONT ]] || { echo "$CMD" ; eval "$CMD" ; CMD="" ; }
         }
       fi
